### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lakani** [lakani/OpenCore#2]
### Milestone I

- [ ] Localization of Resources, at least English for now

- [x] CIF Types -> (Personal , Non Personal)
- [x] CIF
- [x] CIF Class
- [x] CIF Class Companies
 
- [x] (SP_AddGL) should not add the same Ledger with different Nature 
- [x] Channel could Pass Reference number to Post Tran so that it uses instead of generating a new One

Totalling GL :
- [ ] Totalling GL :	Validation on (Totalling GL, Parent GL) 
                Same Company, Currency , Nature , Posting Level 
- [ ] Totalling GL :	Database Structure 
- [ ] Totalling GL :	While Creating
- [ ] Totalling GL :	Balance Retrieval 
- [ ] Totalling GL :	GL Info Retrieval 
- [ ] Totalling GL : Posting
                Should check if there is a corresponding Totalling GL , the Legs should balance 
		        CR = DR of the totalling 
	
- [ ] GL : The Size of GL ??? -> MAX is 35 Digit

- [x] POST TRAN : 
- [x] POST TRAN : POST TRAN 
- [x] POST TRAN : Reversal 

- [ ] Cash Box / Cash Teller / Cash Drawler 

- [ ] make Company, Branch integer not Smaller than that

**Comment by lakani** [comment]
split into sub issues
