### ISSUE TITLE
remove the (DEF_)  prefix from all tables

### ISSUE THREAD

**Issue by lakani** [lakani/OpenCore#84]
SO FAR

- [x] public virtual DbSet<DEF_Zone> DEF_Zone { get; set; }
- [x] public virtual DbSet<DEF_Dep> DEF_Dep { get; set; }
- [x] public virtual DbSet<DEF_Sector> DEF_Sector { get; set; }
- [x] public virtual DbSet<DEF_Unit> DEF_Unit { get; set; }
- [x] public virtual DbSet<DEF_Company> DEF_Company { get; set; }
- [x] public virtual DbSet<DEF_Branch> DEF_Branch { get; set; }
- [x] public virtual DbSet<DEF_GL> DEF_GL { get; set; }
- [x] public virtual DbSet<DEF_CIF_CLASS> DEF_CIF_CLASS { get; set; }
- [x] public virtual DbSet<DEF_CIF> DEF_CIF { get; set; }
- [x] public virtual DbSet<DEF_CIF_PERSONAL> DEF_CIF_PERSONAL { get; set; }
- [x] public virtual DbSet<DEF_Currency>  DEF_Currency { get; set; }
- [x] public virtual DbSet<DEF_ACCT_CLASS> DEF_ACCT_CLASS { get; set; }
- [x] public virtual DbSet<DEF_CK_ACCT> DEF_CK_ACCT { get; set; }
- [x] public virtual DbSet<DEF_Posting> DEF_Posting { get; set; }
- [ ]

**Comment by lakani** [comment]
Done
